# Generated by Django 2.2.6 on 2019-11-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191117_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='movie',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='电影'),
        ),
    ]
