# Generated by Django 2.2.6 on 2019-11-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20191117_0753'),
    ]

    operations = [
    ]
