# Generated by Django 2.2.6 on 2019-11-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='intrests',
            new_name='interests',
        ),
    ]
